### ISSUE TITLE
Build for example project failed

### ISSUE THREAD

**Issue by meyermarcel** [lurado/LDOTiledView#3]
Thanks for this great library and the example app. This repository did his part in helping me understanding CATiledLayer.

I have a build error trying to build the example app. I never used cocoapods before and would say I am a beginner in Swift and iOS programming. So the error could only exist on my machine due my minor skills.

I executed the following steps:

1. `brew install cocoapods`

1. Get versions of macOS, Xcode and Cocoapods

    `sw_vers -productVersion && /usr/bin/xcodebuild -version && pod --version`

    ```
    10.15.4
    Xcode 11.4
    Build version 11E146
    1.9.1
    ```

1. `git clone https://github.com/lurado/LDOTiledView.git`

1. `cd LDOTiledView/Example/`

1. `pod install`

    ```
    Analyzing dependencies
    Downloading dependencies
    Installing LDOTiledView (1.0.0)
    Generating Pods project
    Integrating client project
    Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
    ```

1. `open LDOTiledView.xcodeproj`

1. Trigger *Build and then run the current scheme* in Xcode

    <img width="1010" alt="Screenshot 2020-04-05 at 12 51 25" src="https://user-images.githubusercontent.com/3398801/78472833-3807cd80-773c-11ea-853b-6c2aa6fb8a5d.png">

**Comment by jlnr** [comment]
Hey, glad that you like the library!

The way CocoaPods works is that it generates an additional Xcode project for dependencies (Pods.xcodeproj), and then combines both LDOTiledView.xcodeproj and Pods.xcodeproj into an Xcode workspace called LDOTiledView.xcworkspace. If you open the xcworkspace file, it will compile and run.

**Comment by meyermarcel** [comment]
Perfect! Thanks a lot for the quick response. I have to read more about cocoapods before I create a new issue here.

I assume the steps are common knowledge but just in case I improved the Readme in a [Pull Request](https://github.com/lurado/LDOTiledView/pull/4)
